name: 'integrate'
on: pull_request


jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: |
                    npm install
            -   run: |
                    npm run lint
            -   run: |
                    npm test
            -   run: |
                    npm run build
