name: 'integrate'
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: |
                    npm install
            -   run: |
                    npm test
            -   run: |
                    npm run build
